# Generated by Django 4.0.6 on 2022-11-08 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=10000)),
                ('topic', models.CharField(max_length=10000)),
                ('link', models.CharField(max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('detail', models.TextField()),
                ('started', models.BooleanField(default=False)),
                ('tutorial_time', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('link', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('expire_time', models.DateTimeField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='tutorial_students', to=settings.AUTH_USER_MODEL)),
                ('tutors', models.ManyToManyField(blank=True, related_name='tutorial_tutor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('detail', models.TextField()),
                ('started', models.BooleanField(default=False)),
                ('tutorial_time', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('link', models.TextField()),
                ('expire_time', models.DateTimeField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('category', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='skills_students', to=settings.AUTH_USER_MODEL)),
                ('tutors', models.ManyToManyField(blank=True, related_name='skills_tutor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('state', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('address', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.CharField(blank=True, max_length=200, null=True)),
                ('cat2', models.CharField(blank=True, max_length=200, null=True)),
                ('cat3', models.CharField(blank=True, max_length=200, null=True)),
                ('cat4', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('types', models.TextField(blank=True, null=True)),
                ('action', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_owner', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('material', models.FileField(upload_to='media/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10000, null=True)),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('total_hour', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, default='BEGINNER - ADVANCED', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('classes', models.ManyToManyField(blank=True, to='ustuda.classes')),
                ('materials', models.ManyToManyField(blank=True, to='ustuda.materials')),
                ('schools', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ustuda.schools')),
                ('students', models.ManyToManyField(blank=True, related_name='course_students', to=settings.AUTH_USER_MODEL)),
                ('tutorials', models.ManyToManyField(blank=True, to='ustuda.tutorial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
