# Generated by Django 4.0.6 on 2022-11-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0002_classes_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
