# Generated by Django 4.0.6 on 2022-11-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0003_alter_classes_price_alter_materials_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='image',
            new_name='course_image',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='tutors',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='course_name',
            field=models.CharField(default='Chemistry', max_length=10000),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='level',
            field=models.CharField(default='BEGINNER - ADVANCED', max_length=10000),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='name_of_tutor',
            field=models.CharField(default='Mr Ben', max_length=10000),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='topic',
            field=models.CharField(default='Molecular Structure Of Mass', max_length=10000),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutors_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
