# Generated by Django 4.0.6 on 2022-11-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0004_rename_image_tutorial_course_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['-most_viewed']},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['-most_viewed']},
        ),
        migrations.AlterModelOptions(
            name='materials',
            options={'ordering': ['-most_viewed']},
        ),
        migrations.AlterModelOptions(
            name='schools',
            options={'ordering': ['-most_viewed']},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['-most_viewed']},
        ),
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-most_viewed']},
        ),
        migrations.AddField(
            model_name='classes',
            name='most_viewed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='courses',
            name='most_viewed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='materials',
            name='most_viewed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schools',
            name='most_viewed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skills',
            name='most_viewed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='most_viewed',
            field=models.IntegerField(default=1),
        ),
    ]
