# Generated by Django 4.0.6 on 2022-11-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0005_alter_classes_options_alter_courses_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='address',
            field=models.TextField(default='School information'),
        ),
        migrations.AlterField(
            model_name='schools',
            name='info',
            field=models.TextField(default='School information'),
        ),
    ]
