# Generated by Django 4.0.6 on 2022-11-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0006_alter_schools_address_alter_schools_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='name',
        ),
        migrations.AddField(
            model_name='materials',
            name='course_name',
            field=models.CharField(default='Chemistry', max_length=10000),
        ),
        migrations.AddField(
            model_name='materials',
            name='material_title',
            field=models.CharField(default='Fundamental', max_length=10000),
        ),
        migrations.AlterField(
            model_name='materials',
            name='material',
            field=models.FileField(upload_to='media/bkk'),
        ),
    ]
