# Generated by Django 4.0.6 on 2022-11-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0007_remove_materials_name_materials_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='schools',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_school', to='ustuda.schools'),
        ),
    ]
