# Generated by Django 4.0.6 on 2022-11-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0008_materials_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='levels',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
