# Generated by Django 4.0.6 on 2022-11-13 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0009_courses_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='schools',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_school', to='ustuda.schools'),
        ),
    ]
