# Generated by Django 4.0.6 on 2022-11-13 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ustuda', '0010_classes_schools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ustuda.schools'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ustuda.schools'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ustuda.schools'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
