# Generated by Django 4.0.6 on 2022-11-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0011_alter_classes_schools_alter_courses_schools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='detailed_summary_of_course',
            field=models.TextField(blank=True, default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem quibusdam eum explicabo velit cum mollitia vel numquam repellat', null=True),
        ),
    ]
