# Generated by Django 4.0.6 on 2022-11-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0012_courses_detailed_summary_of_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='total_hour',
            field=models.CharField(blank=True, default='240 hours', max_length=10000, null=True),
        ),
    ]
