# Generated by Django 4.0.6 on 2022-11-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0013_alter_courses_total_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_time',
            field=models.CharField(blank=True, default='2:20', max_length=10000, null=True),
        ),
    ]
