# Generated by Django 4.0.6 on 2022-11-16 08:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ustuda', '0015_courses_brief_about_teacher_courses_teacher_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Announcements',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='notifications',
            new_name='announcement',
        ),
    ]
