# Generated by Django 4.0.6 on 2022-11-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0016_rename_notifications_announcements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='pages',
            field=models.IntegerField(default=1),
        ),
    ]
