# Generated by Django 4.0.6 on 2022-11-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0017_materials_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='levels',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
