# Generated by Django 4.0.6 on 2022-11-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0018_materials_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='levels',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
