# Generated by Django 4.0.6 on 2022-11-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0019_tutorial_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='about_teacher',
            field=models.TextField(blank=True, default='Briefly about tutor', null=True),
        ),
    ]
