# Generated by Django 4.0.6 on 2022-11-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0020_tutorial_about_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='announcement',
            field=models.ManyToManyField(blank=True, related_name='tutorial_announcement', to='ustuda.announcements'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='tutorial_material', to='ustuda.materials'),
        ),
    ]
