# Generated by Django 4.0.6 on 2022-11-23 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ustuda', '0021_tutorial_announcement_tutorial_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='waiting_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='which_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorial_tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
