# Generated by Django 4.0.6 on 2022-11-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0022_tutorial_waiting_tutor_tutorial_which_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.TextField(default='Live tutorial have started'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.TextField(default='Molecular Structure of Matter'),
        ),
    ]
