# Generated by Django 4.0.6 on 2022-11-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0023_alter_notification_action_alter_notification_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='types',
            field=models.CharField(blank=True, default='Leave this field empty if briefing is needed', max_length=100, null=True),
        ),
    ]
