# Generated by Django 4.0.6 on 2022-11-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0024_alter_notification_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
