# Generated by Django 4.0.6 on 2022-11-23 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ustuda', '0025_notification_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='tutorial_time',
            new_name='brief_about_teacher',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='last_seen',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='image',
            new_name='teacher_image_or_logo',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='expire_time',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='link',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='started',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='tutors',
        ),
        migrations.AddField(
            model_name='skills',
            name='announcement',
            field=models.ManyToManyField(blank=True, to='ustuda.announcements'),
        ),
        migrations.AddField(
            model_name='skills',
            name='classes',
            field=models.ManyToManyField(blank=True, to='ustuda.classes'),
        ),
        migrations.AddField(
            model_name='skills',
            name='detailed_summary_of_course',
            field=models.TextField(blank=True, default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem quibusdam eum explicabo velit cum mollitia vel numquam repellat', null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='level',
            field=models.CharField(blank=True, default='BEGINNER,INTERMEDIATE,ADVANCE,BEGINNER - ADVANCE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='levels',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='materials',
            field=models.ManyToManyField(blank=True, to='ustuda.materials'),
        ),
        migrations.AddField(
            model_name='skills',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='title',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='total_hour',
            field=models.CharField(blank=True, default='240 hours', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='level',
            field=models.CharField(default='BEGINNER - ADVANCED', max_length=20),
        ),
        migrations.AlterField(
            model_name='courses',
            name='level',
            field=models.CharField(blank=True, default='BEGINNER - ADVANCED', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='skill_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='level',
            field=models.CharField(default='BEGINNER - ADVANCED', max_length=20),
        ),
    ]
