# Generated by Django 4.0.6 on 2022-11-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0026_rename_tutorial_time_skills_brief_about_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
