# Generated by Django 4.0.6 on 2022-11-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0027_skills_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='manual_skill',
            field=models.BooleanField(default=False),
        ),
    ]
