# Generated by Django 4.0.6 on 2022-11-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0028_skills_manual_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='author',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
