# Generated by Django 4.0.6 on 2022-11-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0029_materials_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='detailed_summary_of_material',
            field=models.TextField(blank=True, default='Materials Details', null=True),
        ),
    ]
