# Generated by Django 4.0.6 on 2022-11-27 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ustuda', '0030_materials_detailed_summary_of_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='material_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
