# Generated by Django 4.0.6 on 2022-11-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0031_materials_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
