# Generated by Django 4.0.6 on 2022-12-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0033_payment_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_information',
            name='transaction_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment_information',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment_information',
            name='item_name',
            field=models.TextField(default=1),
        ),
        migrations.AlterField(
            model_name='payment_information',
            name='item_title',
            field=models.TextField(default=1),
        ),
    ]
