# Generated by Django 4.0.6 on 2022-12-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0036_comments_holder_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments_holder',
            options={},
        ),
        migrations.AddField(
            model_name='courses',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
