# Generated by Django 4.0.6 on 2023-01-12 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0037_alter_comments_holder_options_courses_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorial_singles', to='ustuda.tutorial'),
        ),
    ]
