# Generated by Django 4.0.6 on 2023-01-15 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0040_logged_in_user_jwt_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logged_in_user_jwt_rec',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
