# Generated by Django 4.0.6 on 2023-01-16 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustuda', '0041_alter_logged_in_user_jwt_rec_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logged_in_user_jwt_rec',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
